leftnav:
- identifier: db15987e-3ec0-b30c-4d4e-dbe91581419c
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: ba8c1996-d7ee-cc27-d21f-b61fd4f956e2
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 7d7428f7-d97a-ded6-4eb5-4702aad44388
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 063c38bc-32f6-4a8c-f40d-7c97da289b52
  name: Assignments
  url: /pages/assignments/
  weight: 40
- identifier: 70e5a6b6-5130-6f26-eaae-7079bd7cc2e9
  name: Writing Tips
  parent: 063c38bc-32f6-4a8c-f40d-7c97da289b52
  url: /pages/assignments/writing-tips
  weight: 50
